export const COLOMBIA_LOCATIONS: Record<string, string[]> = {
    "Amazonas": [
        "Leticia",
        "Puerto Nariño"
    ],
    "Antioquia": [
        "Abejorral",
        "Abriaquí",
        "Alejandría",
        "Amagá",
        "Amalfi",
        "Andes",
        "Angelópolis",
        "Angostura",
        "Anorí",
        "Anzá",
        "Apartadó",
        "Arboletes",
        "Argelia",
        "Armenia",
        "Barbosa",
        "Bello",
        "Belmira",
        "Betania",
        "Betulia",
        "Briceño",
        "Buriticá",
        "Caicedo",
        "Caldas",
        "Campamento",
        "Caracolí",
        "Caramanta",
        "Carepa",
        "Carolina",
        "Caucasia",
        "Cañasgordas",
        "Chigorodó",
        "Cisneros",
        "Ciudad Bolívar",
        "Cocorná",
        "Concepción",
        "Concordia",
        "Copacabana",
        "Cáceres",
        "Dabeiba",
        "Donmatías",
        "Ebéjico",
        "El Bagre",
        "El Carmen De Viboral",
        "El Santuario",
        "Entrerríos",
        "Envigado",
        "Fredonia",
        "Frontino",
        "Giraldo",
        "Girardota",
        "Granada",
        "Guadalupe",
        "Guarne",
        "Guatapé",
        "Gómez Plata",
        "Heliconia",
        "Hispania",
        "Itagüí",
        "Ituango",
        "Jardín",
        "Jericó",
        "La Ceja",
        "La Estrella",
        "La Pintada",
        "La Unión",
        "Liborina",
        "Maceo",
        "Marinilla",
        "Medellín",
        "Montebello",
        "Murindó",
        "Mutatá",
        "Nariño",
        "Nechí",
        "Necoclí",
        "Olaya",
        "Peque",
        "Peñol",
        "Pueblorrico",
        "Puerto Berrío",
        "Puerto Nare",
        "Puerto Triunfo",
        "Remedios",
        "Retiro",
        "Rionegro",
        "Sabanalarga",
        "Sabaneta",
        "Salgar",
        "San Andrés De Cuerquía",
        "San Carlos",
        "San Francisco",
        "San Jerónimo",
        "San José De La Montaña",
        "San Juan De Urabá",
        "San Luis",
        "San Pedro De Los Milagros",
        "San Pedro De Urabá",
        "San Rafael",
        "San Roque",
        "San Vicente Ferrer",
        "Santa Bárbara",
        "Santa Fé De Antioquia",
        "Santa Rosa De Osos",
        "Santo Domingo",
        "Segovia",
        "Sonsón",
        "Sopetrán",
        "Tarazà",
        "Tarso",
        "Titiribí",
        "Toledo",
        "Turbo",
        "Támesis",
        "Uramita",
        "Urrao",
        "Valdivia",
        "Valparaíso",
        "Vegachí",
        "Venecia",
        "Vigía Del Fuerte",
        "Yalí",
        "Yarumal",
        "Yolombó",
        "Yondó",
        "Zaragoza"
    ],
    "Arauca": [
        "Arauca",
        "Arauquita",
        "Cravo Norte",
        "Fortul",
        "Puerto Rondón",
        "Saravena",
        "Tame"
    ],
    "Archipiélago De San Andrés, Providencia Y Santa Catalina": [
        "Providencia"
    ],
    "Atlántico": [
        "Baranoa",
        "Barranquilla",
        "Campo De La Cruz",
        "Candelaria",
        "Galapa",
        "Juan De Acosta",
        "Luruaco",
        "Malambo",
        "Manatí",
        "Palmar De Varela",
        "Piojó",
        "Polonuevo",
        "Ponedera",
        "Puerto Colombia",
        "Repelón",
        "Sabanagrande",
        "Sabanalarga",
        "Santa Lucía",
        "Santo Tomás",
        "Soledad",
        "Suan",
        "Tubará",
        "Usiacurí"
    ],
    "Bogotá, D.C.": [
        "Bogotá, D.C."
    ],
    "Bolívar": [
        "Achí",
        "Altos Del Rosario",
        "Arenal",
        "Arjona",
        "Arroyohondo",
        "Barranco De Loba",
        "Calamar",
        "Cantagallo",
        "Cartagena De Indias",
        "Cicuco",
        "Clemencia",
        "Córdoba",
        "El Carmen De Bolívar",
        "El Guamo",
        "El Peñón",
        "Hatillo De Loba",
        "Magangué",
        "Mahates",
        "Margarita",
        "María La Baja",
        "Montecristo",
        "Morales",
        "Norosí",
        "Pinillos",
        "Regidor",
        "Río Viejo",
        "San Cristóbal",
        "San Estanislao",
        "San Fernando",
        "San Jacinto",
        "San Jacinto Del Cauca",
        "San Juan Nepomuceno",
        "San Martín De Loba",
        "San Pablo",
        "Santa Catalina",
        "Santa Cruz De Mompox",
        "Santa Rosa",
        "Santa Rosa Del Sur",
        "Simití",
        "Soplaviento",
        "Talaigua Nuevo",
        "Tiquisio",
        "Turbaco",
        "Turbana",
        "Villanueva",
        "Zambrano"
    ],
    "Boyacá": [
        "Almeida",
        "Aquitania",
        "Arcabuco",
        "Belén",
        "Berbeo",
        "Betéitiva",
        "Boavita",
        "Boyacá",
        "Briceño",
        "Buenavista",
        "Busbanzá",
        "Caldas",
        "Campohermoso",
        "Cerinza",
        "Chinavita",
        "Chiquinquirá",
        "Chiscas",
        "Chita",
        "Chitaraque",
        "Chivatá",
        "Chivor",
        "Chíquiza",
        "Ciénega",
        "Coper",
        "Corrales",
        "Covarachía",
        "Cubará",
        "Cucaita",
        "Cuítiva",
        "Cómbita",
        "Duitama",
        "El Cocuy",
        "El Espino",
        "Firavitoba",
        "Floresta",
        "Gachantivá",
        "Garagoa",
        "Guacamayas",
        "Guateque",
        "Guayatá",
        "Gámeza",
        "Güicán De La Sierra",
        "Iza",
        "Jenesano",
        "Jericó",
        "La Capilla",
        "La Uvita",
        "La Victoria",
        "Labranzagrande",
        "Macanal",
        "Maripí",
        "Miraflores",
        "Mongua",
        "Monguí",
        "Moniquirá",
        "Motavita",
        "Muzo",
        "Nobsa",
        "Nuevo Colón",
        "Oicatá",
        "Otanche",
        "Pachavita",
        "Paipa",
        "Pajarito",
        "Panqueba",
        "Pauna",
        "Paya",
        "Paz De Río",
        "Pesca",
        "Pisba",
        "Puerto Boyacá",
        "Páez",
        "Quípama",
        "Ramiriquí",
        "Rondón",
        "Ráquira",
        "Saboyá",
        "Samacá",
        "San Eduardo",
        "San José De Pare",
        "San Luis De Gaceno",
        "San Mateo",
        "San Miguel De Sema",
        "San Pablo De Borbur",
        "Santa María",
        "Santa Rosa De Viterbo",
        "Santa Sofía",
        "Santana",
        "Sativanorte",
        "Sativasur",
        "Siachoque",
        "Soatá",
        "Socha",
        "Socotá",
        "Sogamoso",
        "Somondoco",
        "Sora",
        "Soracá",
        "Sotaquirá",
        "Susacón",
        "Sutamarchán",
        "Sutatenza",
        "Sáchica",
        "Tasco",
        "Tenza",
        "Tibaná",
        "Tibasosa",
        "Tinjacá",
        "Tipacoque",
        "Toca",
        "Togüí",
        "Tota",
        "Tunja",
        "Tununguá",
        "Turmequé",
        "Tuta",
        "Tutazá",
        "Tópaga",
        "Ventaquemada",
        "Villa De Leyva",
        "Viracachá",
        "Zetaquira",
        "Úmbita"
    ],
    "Caldas": [
        "Aguadas",
        "Anserma",
        "Aranzazu",
        "Belalcázar",
        "Chinchiná",
        "Filadelfia",
        "La Dorada",
        "La Merced",
        "Manizales",
        "Manzanares",
        "Marmato",
        "Marquetalia",
        "Marulanda",
        "Neira",
        "Norcasia",
        "Palestina",
        "Pensilvania",
        "Pácora",
        "Riosucio",
        "Risaralda",
        "Salamina",
        "Samaná",
        "San José",
        "Supía",
        "Victoria",
        "Villamaría",
        "Viterbo"
    ],
    "Caquetá": [
        "Albania",
        "Belén De Los Andaquíes",
        "Cartagena Del Chairá",
        "Curillo",
        "El Doncello",
        "El Paujíl",
        "Florencia",
        "La Montañita",
        "Milán",
        "Morelia",
        "Puerto Rico",
        "San José Del Fragua",
        "San Vicente Del Caguán",
        "Solano",
        "Solita",
        "Valparaíso"
    ],
    "Casanare": [
        "Aguazul",
        "Chámeza",
        "Hato Corozal",
        "La Salina",
        "Maní",
        "Monterrey",
        "Nunchía",
        "Orocué",
        "Paz De Ariporo",
        "Pore",
        "Recetor",
        "Sabanalarga",
        "San Luis De Palenque",
        "Sácama",
        "Tauramena",
        "Trinidad",
        "Támara",
        "Villanueva",
        "Yopal"
    ],
    "Cauca": [
        "Almaguer",
        "Argelia",
        "Balboa",
        "Bolívar",
        "Buenos Aires",
        "Cajibío",
        "Caldono",
        "Caloto",
        "Corinto",
        "El Tambo",
        "Florencia",
        "Guachené",
        "Guapi",
        "Inzá",
        "Jambaló",
        "La Sierra",
        "La Vega",
        "López De Micay",
        "Mercaderes",
        "Miranda",
        "Morales",
        "Padilla",
        "Patía",
        "Piamonte",
        "Piendamó - Tunía",
        "Popayán",
        "Puerto Tejada",
        "Puracé",
        "Páez",
        "Rosas",
        "San Sebastián",
        "Santa Rosa",
        "Santander De Quilichao",
        "Silvia",
        "Sotará Paispamba",
        "Sucre",
        "Suárez",
        "Timbiquí",
        "Timbío",
        "Toribío",
        "Totoró",
        "Villa Rica"
    ],
    "Cesar": [
        "Aguachica",
        "Agustín Codazzi",
        "Astrea",
        "Becerril",
        "Bosconia",
        "Chimichagua",
        "Chiriguaná",
        "Curumaní",
        "El Copey",
        "El Paso",
        "Gamarra",
        "González",
        "La Gloria",
        "La Jagua De Ibirico",
        "La Paz",
        "Manaure Balcón Del Cesar",
        "Pailitas",
        "Pelaya",
        "Pueblo Bello",
        "Río De Oro",
        "San Alberto",
        "San Diego",
        "San Martín",
        "Tamalameque",
        "Valledupar"
    ],
    "Chocó": [
        "Acandí",
        "Alto Baudó",
        "Atrato",
        "Bagadó",
        "Bahía Solano",
        "Bajo Baudó",
        "Bojayá",
        "Carmen Del Darién",
        "Condoto",
        "Cértegui",
        "El Cantón Del San Pablo",
        "El Carmen De Atrato",
        "El Litoral Del San Juan",
        "Istmina",
        "Juradó",
        "Lloró",
        "Medio Atrato",
        "Medio Baudó",
        "Medio San Juan",
        "Nuevo Belén De Bajirá",
        "Nuquí",
        "Nóvita",
        "Quibdó",
        "Riosucio",
        "Río Iró",
        "Río Quito",
        "San José Del Palmar",
        "Sipí",
        "Tadó",
        "Unguía",
        "Unión Panamericana"
    ],
    "Cundinamarca": [
        "Agua De Dios",
        "Albán",
        "Anapoima",
        "Anolaima",
        "Apulo",
        "Arbeláez",
        "Beltrán",
        "Bituima",
        "Bojacá",
        "Cabrera",
        "Cachipay",
        "Cajicá",
        "Caparrapí",
        "Carmen De Carupa",
        "Chaguaní",
        "Chipaque",
        "Choachí",
        "Chocontá",
        "Chía",
        "Cogua",
        "Cota",
        "Cucunubá",
        "Cáqueza",
        "El Colegio",
        "El Peñón",
        "El Rosal",
        "Facatativá",
        "Fosca",
        "Funza",
        "Fusagasugá",
        "Fómeque",
        "Fúquene",
        "Gachalá",
        "Gachancipá",
        "Gachetá",
        "Gama",
        "Girardot",
        "Granada",
        "Guachetá",
        "Guaduas",
        "Guasca",
        "Guataquí",
        "Guatavita",
        "Guayabal De Síquima",
        "Guayabetal",
        "Gutiérrez",
        "Jerusalén",
        "Junín",
        "La Calera",
        "La Mesa",
        "La Palma",
        "La Peña",
        "La Vega",
        "Lenguazaque",
        "Machetá",
        "Madrid",
        "Manta",
        "Medina",
        "Mosquera",
        "Nariño",
        "Nemocón",
        "Nilo",
        "Nimaima",
        "Nocaima",
        "Pacho",
        "Paime",
        "Pandi",
        "Paratebueno",
        "Pasca",
        "Puerto Salgar",
        "Pulí",
        "Quebradanegra",
        "Quetame",
        "Quipile",
        "Ricaurte",
        "San Antonio Del Tequendama",
        "San Bernardo",
        "San Cayetano",
        "San Francisco",
        "San Juan De Rioseco",
        "Sasaima",
        "Sesquilé",
        "Sibaté",
        "Silvania",
        "Simijaca",
        "Soacha",
        "Sopó",
        "Subachoque",
        "Suesca",
        "Supatá",
        "Susa",
        "Sutatausa",
        "Tabio",
        "Tausa",
        "Tena",
        "Tenjo",
        "Tibacuy",
        "Tibirita",
        "Tocaima",
        "Tocancipá",
        "Topaipí",
        "Ubalá",
        "Ubaque",
        "Une",
        "Venecia",
        "Vergara",
        "Vianí",
        "Villa De San Diego De Ubaté",
        "Villagómez",
        "Villapinzón",
        "Villeta",
        "Viotá",
        "Yacopí",
        "Zipacón",
        "Zipaquirá",
        "Útica"
    ],
    "Córdoba": [
        "Ayapel",
        "Buenavista",
        "Canalete",
        "Cereté",
        "Chimá",
        "Chinú",
        "Ciénaga De Oro",
        "Cotorra",
        "La Apartada",
        "Lorica",
        "Los Córdobas",
        "Momil",
        "Montelíbano",
        "Montería",
        "Moñitos",
        "Planeta Rica",
        "Pueblo Nuevo",
        "Puerto Escondido",
        "Puerto Libertador",
        "Purísima De La Concepción",
        "Sahagún",
        "San Andrés De Sotavento",
        "San Antero",
        "San Bernardo Del Viento",
        "San Carlos",
        "San José De Uré",
        "San Pelayo",
        "Tierralta",
        "Tuchín",
        "Valencia"
    ],
    "Guainía": [
        "Barrancominas",
        "Inírida"
    ],
    "Guaviare": [
        "Calamar",
        "El Retorno",
        "Miraflores",
        "San José Del Guaviare"
    ],
    "Huila": [
        "Acevedo",
        "Agrado",
        "Aipe",
        "Algeciras",
        "Altamira",
        "Baraya",
        "Campoalegre",
        "Colombia",
        "Elías",
        "Garzón",
        "Gigante",
        "Guadalupe",
        "Hobo",
        "Isnos",
        "La Argentina",
        "La Plata",
        "Neiva",
        "Nátaga",
        "Oporapa",
        "Paicol",
        "Palermo",
        "Palestina",
        "Pital",
        "Pitalito",
        "Rivera",
        "Saladoblanco",
        "San Agustín",
        "Santa María",
        "Suaza",
        "Tarqui",
        "Tello",
        "Teruel",
        "Tesalia",
        "Timaná",
        "Villavieja",
        "Yaguará",
        "Íquira"
    ],
    "La Guajira": [
        "Albania",
        "Barrancas",
        "Dibulla",
        "Distracción",
        "El Molino",
        "Fonseca",
        "Hatonuevo",
        "La Jagua Del Pilar",
        "Maicao",
        "Manaure",
        "Riohacha",
        "San Juan Del Cesar",
        "Uribia",
        "Urumita",
        "Villanueva"
    ],
    "Magdalena": [
        "Algarrobo",
        "Aracataca",
        "Ariguaní",
        "Cerro De San Antonio",
        "Chivolo",
        "Ciénaga",
        "Concordia",
        "El Banco",
        "El Piñón",
        "El Retén",
        "Fundación",
        "Guamal",
        "Nueva Granada",
        "Pedraza",
        "Pijiño Del Carmen",
        "Pivijay",
        "Plato",
        "Puebloviejo",
        "Remolino",
        "Sabanas De San Ángel",
        "Salamina",
        "San Sebastián De Buenavista",
        "San Zenón",
        "Santa Ana",
        "Santa Bárbara De Pinto",
        "Santa Marta",
        "Sitionuevo",
        "Tenerife",
        "Zapayán",
        "Zona Bananera"
    ],
    "Meta": [
        "Acacías",
        "Barranca De Upía",
        "Cabuyaro",
        "Castilla La Nueva",
        "Cubarral",
        "Cumaral",
        "El Calvario",
        "El Castillo",
        "El Dorado",
        "Fuente De Oro",
        "Granada",
        "Guamal",
        "La Macarena",
        "Lejanías",
        "Mapiripán",
        "Mesetas",
        "Puerto Concordia",
        "Puerto Gaitán",
        "Puerto Lleras",
        "Puerto López",
        "Puerto Rico",
        "Restrepo",
        "San Carlos De Guaroa",
        "San Juan De Arama",
        "San Juanito",
        "San Martín",
        "Uribe",
        "Villavicencio",
        "Vistahermosa"
    ],
    "Nariño": [
        "Albán",
        "Aldana",
        "Ancuya",
        "Arboleda",
        "Barbacoas",
        "Belén",
        "Buesaco",
        "Chachagüí",
        "Colón",
        "Consacá",
        "Contadero",
        "Cuaspud Carlosama",
        "Cumbal",
        "Cumbitara",
        "Córdoba",
        "El Charco",
        "El Peñol",
        "El Rosario",
        "El Tablón De Gómez",
        "El Tambo",
        "Francisco Pizarro",
        "Funes",
        "Guachucal",
        "Guaitarilla",
        "Gualmatán",
        "Iles",
        "Imués",
        "Ipiales",
        "La Cruz",
        "La Florida",
        "La Llanada",
        "La Tola",
        "La Unión",
        "Leiva",
        "Linares",
        "Los Andes",
        "Magüí",
        "Mallama",
        "Mosquera",
        "Nariño",
        "Olaya Herrera",
        "Ospina",
        "Pasto",
        "Policarpa",
        "Potosí",
        "Providencia",
        "Puerres",
        "Pupiales",
        "Ricaurte",
        "Roberto Payán",
        "Samaniego",
        "San Andrés De Tumaco",
        "San Bernardo",
        "San Lorenzo",
        "San Pablo",
        "San Pedro De Cartago",
        "Sandoná",
        "Santa Bárbara",
        "Santacruz",
        "Sapuyes",
        "Taminango",
        "Tangua",
        "Túquerres",
        "Yacuanquer"
    ],
    "Norte De Santander": [
        "Arboledas",
        "Bochalema",
        "Bucarasica",
        "Chinácota",
        "Chitagá",
        "Convención",
        "Cucutilla",
        "Cáchira",
        "Cácota",
        "Durania",
        "El Carmen",
        "El Tarra",
        "El Zulia",
        "Gramalote",
        "Hacarí",
        "Herrán",
        "La Esperanza",
        "La Playa",
        "Labateca",
        "Los Patios",
        "Lourdes",
        "Mutiscua",
        "Ocaña",
        "Pamplona",
        "Pamplonita",
        "Puerto Santander",
        "Ragonvalia",
        "Salazar",
        "San Calixto",
        "San Cayetano",
        "San José De Cúcuta",
        "Santiago",
        "Sardinata",
        "Silos",
        "Teorama",
        "Tibú",
        "Toledo",
        "Villa Caro",
        "Villa Del Rosario",
        "Ábrego"
    ],
    "Putumayo": [
        "Colón",
        "Mocoa",
        "Orito",
        "Puerto Asís",
        "Puerto Caicedo",
        "Puerto Guzmán",
        "Puerto Leguízamo",
        "San Francisco",
        "San Miguel",
        "Santiago",
        "Sibundoy",
        "Valle Del Guamuez",
        "Villagarzón"
    ],
    "Quindío": [
        "Armenia",
        "Buenavista",
        "Calarcá",
        "Circasia",
        "Córdoba",
        "Filandia",
        "Génova",
        "La Tebaida",
        "Montenegro",
        "Pijao",
        "Quimbaya",
        "Salento"
    ],
    "Risaralda": [
        "Apía",
        "Balboa",
        "Belén De Umbría",
        "Dosquebradas",
        "Guática",
        "La Celia",
        "La Virginia",
        "Marsella",
        "Mistrató",
        "Pereira",
        "Pueblo Rico",
        "Quinchía",
        "Santa Rosa De Cabal",
        "Santuario"
    ],
    "Santander": [
        "Aguada",
        "Albania",
        "Aratoca",
        "Barbosa",
        "Barichara",
        "Barrancabermeja",
        "Betulia",
        "Bolívar",
        "Bucaramanga",
        "Cabrera",
        "California",
        "Capitanejo",
        "Carcasí",
        "Cepitá",
        "Cerrito",
        "Charalá",
        "Charta",
        "Chima",
        "Chipatá",
        "Cimitarra",
        "Concepción",
        "Confines",
        "Contratación",
        "Coromoro",
        "Curití",
        "El Carmen De Chucurí",
        "El Guacamayo",
        "El Peñón",
        "El Playón",
        "Encino",
        "Enciso",
        "Floridablanca",
        "Florián",
        "Galán",
        "Girón",
        "Guaca",
        "Guadalupe",
        "Guapotá",
        "Guavatá",
        "Gámbita",
        "Güepsa",
        "Hato",
        "Jesús María",
        "Jordán",
        "La Belleza",
        "La Paz",
        "Landázuri",
        "Lebrija",
        "Los Santos",
        "Macaravita",
        "Matanza",
        "Mogotes",
        "Molagavita",
        "Málaga",
        "Ocamonte",
        "Oiba",
        "Onzaga",
        "Palmar",
        "Palmas Del Socorro",
        "Piedecuesta",
        "Pinchote",
        "Puente Nacional",
        "Puerto Parra",
        "Puerto Wilches",
        "Páramo",
        "Rionegro",
        "Sabana De Torres",
        "San Andrés",
        "San Benito",
        "San Gil",
        "San Joaquín",
        "San José De Miranda",
        "San Miguel",
        "San Vicente De Chucurí",
        "Santa Bárbara",
        "Santa Helena Del Opón",
        "Simacota",
        "Socorro",
        "Suaita",
        "Sucre",
        "Suratá",
        "Tona",
        "Valle De San José",
        "Vetas",
        "Villanueva",
        "Vélez",
        "Zapatoca"
    ],
    "Sucre": [
        "Buenavista",
        "Caimito",
        "Chalán",
        "Colosó",
        "Corozal",
        "Coveñas",
        "El Roble",
        "Galeras",
        "Guaranda",
        "La Unión",
        "Los Palmitos",
        "Majagual",
        "Morroa",
        "Ovejas",
        "Palmito",
        "Sampués",
        "San Benito Abad",
        "San José De Toluviejo",
        "San Juan De Betulia",
        "San Luis De Sincé",
        "San Marcos",
        "San Onofre",
        "San Pedro",
        "Santiago De Tolú",
        "Sincelejo",
        "Sucre"
    ],
    "Tolima": [
        "Alpujarra",
        "Alvarado",
        "Ambalema",
        "Anzoátegui",
        "Armero",
        "Ataco",
        "Cajamarca",
        "Carmen De Apicalá",
        "Casabianca",
        "Chaparral",
        "Coello",
        "Coyaima",
        "Cunday",
        "Dolores",
        "Espinal",
        "Falan",
        "Flandes",
        "Fresno",
        "Guamo",
        "Herveo",
        "Honda",
        "Ibagué",
        "Icononzo",
        "Lérida",
        "Líbano",
        "Melgar",
        "Murillo",
        "Natagaima",
        "Ortega",
        "Palocabildo",
        "Piedras",
        "Planadas",
        "Prado",
        "Purificación",
        "Rioblanco",
        "Roncesvalles",
        "Rovira",
        "Saldaña",
        "San Antonio",
        "San Luis",
        "San Sebastián De Mariquita",
        "Santa Isabel",
        "Suárez",
        "Valle De San Juan",
        "Venadillo",
        "Villahermosa",
        "Villarrica"
    ],
    "Valle Del Cauca": [
        "Alcalá",
        "Andalucía",
        "Ansermanuevo",
        "Argelia",
        "Bolívar",
        "Buenaventura",
        "Bugalagrande",
        "Caicedonia",
        "Calima",
        "Candelaria",
        "Cartago",
        "Dagua",
        "El Cairo",
        "El Cerrito",
        "El Dovio",
        "El Águila",
        "Florida",
        "Ginebra",
        "Guacarí",
        "Guadalajara De Buga",
        "Jamundí",
        "La Cumbre",
        "La Unión",
        "La Victoria",
        "Obando",
        "Palmira",
        "Pradera",
        "Restrepo",
        "Riofrío",
        "Roldanillo",
        "San Pedro",
        "Santiago De Cali",
        "Sevilla",
        "Toro",
        "Trujillo",
        "Tuluá",
        "Ulloa",
        "Versalles",
        "Vijes",
        "Yotoco",
        "Yumbo",
        "Zarzal"
    ],
    "Vaupés": [
        "Carurú",
        "Mitú",
        "Taraira"
    ],
    "Vichada": [
        "Cumaribo",
        "La Primavera",
        "Puerto Carreño",
        "Santa Rosalía"
    ]
};
